const labels: Record<string, string> = {
  READY: '준비 완료',
  PENDING: '대기 중',
  FAILED: '실패',
  PROCESSING: '처리 중',
  NEEDS_MORE_SAMPLES: '샘플 부족',
  REVOKED: '철회됨',
  NEED_MORE_INFO: '추가 정보 필요',
  APPROVED: '승인됨',
  REJECTED: '거절됨',
  EXPIRED: '만료됨',
  REVIEWING: '검토 중',
  RESOLVED: '해결됨',
  ACTION_TAKEN: '조치 완료',
  COMPLETED: '완료',
  CANCELLED: '취소됨',
  GENERATED: '생성 완료',
  DRAFT: '초안',
  ACTIVE: '활성',
  DISABLED: '비활성',
  USER_CONFIRMED: '사용자 확인 완료',
  ADMIN_APPROVED: '관리자 승인 완료',
  NOT_REVIEWED: '검토 전',
  OWNER: '소유자',
  MEMBER: '멤버',
  VIEWER: '보기 전용',
  USER: '사용자',
  PERSONA: '페르소나',
  SYSTEM: '시스템',
  TARGET: '기억 대상',
  TARGET_MEDIA: '대상 미디어',
  CONSENT: '동의',
  VERIFICATION_REQUEST: '입증 요청',
  PERSONA_CHAT: '페르소나 채팅',
  PERSONA_MESSAGE: '페르소나 메시지',
  VOICE_PROFILE: '음성 프로필',
  DELETION_REQUEST: '삭제 요청',
  REPORT: '신고',
  PHOTO_MEMORY: '사진 기억',
  STORYBOOK: '스토리북',
  SHARE_LINK: '공유 링크',
  MEMORY_GROUP: '기억 그룹',
  ACCOUNT: '계정',
  VOICE_CALL_SESSION: '음성 통화 세션',
  FAMILY_RELATION_CERTIFICATE: '가족관계증명서',
  ID_CARD: '신분증',
  SELF_DECLARATION: '자기 진술',
  OTHER: '기타',
  TARGET_PROFILE: '대상 프로필',
  SELF_STORY: '나의 이야기',
  PRIVATE: '비공개',
  LINK: '링크 공유',
  GROUP: '그룹 공유',
  PUBLIC: '공개',
  target_profile_consent: '대상 프로필 동의',
  photo_upload_consent: '사진 업로드 동의',
  voice_upload_consent: '음성 업로드 동의',
  voice_cloning_consent: '음성 복제 동의',
  ai_persona_creation_consent: 'AI 페르소나 생성 동의',
  ai_response_notice_consent: 'AI 응답 고지 동의',
  storybook_share_consent: '스토리북 공유 동의',
  group_share_consent: '그룹 공유 동의',
  data_retention_consent: '데이터 보관 동의',
  third_party_ai_processing_consent: '제3자 AI 처리 동의',
  voice_collection: '음성 수집',
  photo_collection: '사진 수집',
  persona_creation: '페르소나 생성',
  data_usage: '데이터 사용',
  ai_processing: 'AI 처리',
  ai_response_notice: 'AI 응답 고지',
  storybook_share: '스토리북 공유',
  parent: '부모',
  grandparent: '조부모',
  friend: '친구',
  romantic: '연인',
  self: '본인',
  other: '기타',
  disconnected: '연결 안 됨',
  connecting: '연결 중',
  connected: '연결됨',
  recording: '녹음 중',
  processing: '처리 중',
  ended: '종료됨',
  reviewing: '검토 시작',
  resolve: '해결 처리',
  reject: '거절',
  'action-taken': '조치 완료',
}

export function getDisplayLabel(value: string | null | undefined) {
  if (!value) {
    return '없음'
  }

  return labels[value] ?? value
}
